### ISSUE TITLE
Can't even get jar to execute

### ISSUE THREAD

**Issue by IndustrialOne** [tesseract4java/tesseract4java#46]
C:\Users\Admin>java -jar C:\Users\Admin\Desktop\tesseract4java-0.1.0-windows-x86.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/vorb/tesseract/gui/controller/
TesseractController : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

---------------------------
Java Virtual Machine Launcher
---------------------------
A Java Exception has occurred.
---------------------------
OK   
---------------------------

Am I using the wrong version of Java or something?

**Comment by pvorb** [comment]
Which vwrsion of Java are you using? To answer this question, open a Terminal and run the command `java -version`.

**Comment by IndustrialOne** [comment]
I was using 1.8 but I think I didn't have SDK 1.8 installed on that PC. It's running on this one with Java 1.8.
But I can't seem to load a project. I have pointed the directory with my PNG file but nothing is showing up in the preview or anything that suggests it was loaded.

**Comment by JHB-JAVA** [comment]
Excuse me ! the dependency "ocrevalUAtion" was not found in maven respository。

**Comment by pvorb** [comment]
I'm closing this issue since the original issue was solved by using the correct JDK version. Please open a new issue with more details on your next problem.
